<?php
/**
 * @author      Webjump Develop Team <dev@webjump.com.br>
 * @copyright   2022 Webjump (http://www.webjump.com.br)
 * @license     http://www.webjump.com.br Copyright
 * @link        http://www.webjump.com.br
 */

declare(strict_types=1);

use Webjump\PetName\ViewModel\ShowPetNameAfterLogin;
use Magento\Customer\Block\Account\Customer;

/**
 * @var Customer $block
 * @var ShowPetNameAfterLogin $viewModel
 */


$viewModel = $block->getViewModel();

?>
<?php
try {
    if ($viewModel->isLoggedIn() && $viewModel->isModuleEnable()) :?>
        <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?= $block->escapeHtml(__('Change')) ?></span>
            </button>
        </span>
            <script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "customer": {
                                    "component": "Magento_Customer/js/view/customer"
                                }
                            }
                        }
                    }
                }
            </script>
            <?php if ($block->getChildHtml()) :?>
                <div class="customer-menu" data-target="dropdown">
                    <?= $block->getChildHtml() ?>
                </div>
            <?php endif; ?>
        </li>
<?php
    endif;
} catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
}
?>
