<?php
/**
 * @author      Webjump Develop Team <dev@webjump.com.br>
 * @copyright   2022 Webjump (http://www.webjump.com.br)
 * @license     http://www.webjump.com.br Copyright
 * @link        http://www.webjump.com.br
 */

use Magento\Framework\View\Element\Template;
use Webjump\PetName\ViewModel\ShowPetNameAfterLogin;

/** @var Template $block */
/** @var ShowPetNameAfterLogin $viewModel */

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->isLoggedIn() && $viewModel->isModuleEnable()): ?>
    <li class="customer-welcome">
        <a href="#">
            <?php echo __(
                'Nome do Pet: '
                . $viewModel->getPetNameCustomer()
                . " | Tipo: "
                . $viewModel->getPetKindCustomer())
            ?>
        </a>
    </li>
<?php endif; ?>
